echo "backend:
  name: git-gateway
  branch: main
site_url: https://pitturanostra.netlify.app

media_folder: 'public/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'pages'
    label: 'Pages existantes'
    files:
      - file: 'src/pages/index.html'
        label: 'Accueil'
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Contenu', name: 'body', widget: 'markdown' }" > public\admin\config.yml
